name: .NET Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack
      run: dotnet pack -c Release --no-restore --include-symbols --include-source -o:package
    - uses: actions/upload-artifact@v2
      with: 
        name: nuget
        path: ./package/*.nupkg
    - name: Deploy
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      run: dotnet nuget push "./package/*.nupkg" -s https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}}

  


